#!/usr/bin/env python3
"""Generate each Antigravity plugin's rules/AGENTS.md from the canonical Claude rules.

Antigravity plugin rules are one plain-markdown AGENTS.md per plugin, always on while the plugin is
enabled (bundled agy-customizations docs, plugins.md and rules.md). This script builds them from
claude/home/rules/** and shared/guidance/design-standards.md so the three layers cannot drift.
Run with --check in CI to fail when a generated file is stale.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LIMIT = 24_000  # bytes per rule file, per the bundled rules.md

# Claude wording to Antigravity wording. Order matters, longer keys first.
SUBSTITUTIONS = [
    ('`~/.claude/rules/design-standards.md`', 'the design-kit rules (`~/.gemini/config/guidance/design-standards.md`)'),
    ('~/.claude/rules/design-standards.md', 'the design-kit rules'),
    ('`~/.claude/rules/android/', '`the android-kit rules, section '),
    ('`~/.claude/rules/ios/', '`the ios-kit rules, section '),
    ('~/.claude/machine.md', '~/.gemini/config/machine.md'),
    ('~/.claude/', '~/.gemini/config/'),
    ('android-kit:standards', 'android-standards'),
    ('ios-kit:standards', 'ios-standards'),
    ('design-kit:standards', 'design-standards'),
    ('/android-kit:', '/android-'),
    ('/ios-kit:', '/ios-'),
    ('`CLAUDE.md`', '`AGENTS.md` (or `GEMINI.md`)'),
    ('CLAUDE.md', 'AGENTS.md'),
]

KITS = {
    'android-kit': {
        'title': 'Android and Kotlin rules',
        'sources': ['claude/home/rules/android/kotlin-style.md', 'claude/home/rules/android/compose.md',
                    'claude/home/rules/android/ui-events.md', 'claude/home/rules/android/testing.md'],
        'delegation': [
            'Delegate current platform research to `android-researcher` (`model: flash`, read-only tools).',
            'Delegate non-trivial diff review to `android-reviewer` (`model: pro`, read-only tools).',
            'Delegate test execution and emulator verification to `android-verifier` (`model: flash`).',
            'Plugin agents load with the plugin. Invoke them with `invoke_subagent`, give each a bounded task, and re-check findings before reporting them.',
        ],
    },
    'ios-kit': {
        'title': 'iOS and Swift rules',
        'sources': ['claude/home/rules/ios/swift-style.md', 'claude/home/rules/ios/swiftui.md',
                    'claude/home/rules/ios/ui-events.md', 'claude/home/rules/ios/testing.md'],
        'delegation': [
            'Delegate current platform research to `ios-researcher` (`model: flash`, read-only tools).',
            'Delegate non-trivial diff review to `ios-reviewer` (`model: pro`, read-only tools).',
            'Delegate tests and simulator evidence to `ios-verifier` (`model: flash`).',
            'Plugin agents load with the plugin. Invoke them with `invoke_subagent`, give each a bounded task, and re-check findings before reporting them.',
        ],
    },
    'design-kit': {
        'title': 'Design rules',
        'sources': ['shared/guidance/design-standards.md'],
        'delegation': [
            'The `design-standards` skill holds the sources, the rationale for house rules and the platform APIs per rule.',
            'Delegate UI diffs, component audits and screen reviews to `ui-reviewer` (`model: pro`, read-only tools) through `invoke_subagent`. Give it a bounded task and re-check its findings before reporting them.',
        ],
    },
}


def strip_frontmatter(text):
    if text.startswith('---\n'):
        end = text.find('\n---\n', 4)
        if end != -1:
            return text[end + 5:]
    return text


def paths_of(text):
    """The `paths:` globs of a Claude rule, for the scope line."""
    if not text.startswith('---\n'):
        return []
    block = text[4:text.find('\n---\n', 4)]
    match = re.search(r'^paths:\s*\n((?:\s+-\s+.*\n?)+)', block + '\n', re.M)
    return re.findall(r'^\s+-\s+"?([^"\n]+)"?\s*$', match.group(1), re.M) if match else []


def adapt(text):
    for old, new in SUBSTITUTIONS:
        text = text.replace(old, new)
    return text


def render(kit, spec):
    parts = [f'# {spec["title"]}', '',
             '<!-- Generated by antigravity/scripts/sync_rules.py from the canonical Claude rules. Do not edit by hand. -->', '',
             'These rules apply while this plugin is enabled. The Claude layer scopes each section to file paths. Antigravity loads the whole file, so apply each section to the files its scope line names.', '',
             '## Subagents and delegation', '']
    parts += [f'- {line}' for line in spec['delegation']]
    for rel in spec['sources']:
        source = ROOT / rel
        raw = source.read_text()
        body = adapt(strip_frontmatter(raw)).strip()
        globs = paths_of(raw)
        body = re.sub(r'^# ', '## ', body, count=1, flags=re.M)
        parts += ['', body]
        if globs:
            parts.append('')
            parts.append('Scope: ' + ', '.join(f'`{g}`' for g in globs) + '.')
    return '\n'.join(parts).rstrip() + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='exit 1 when a generated file is stale instead of writing it')
    args = parser.parse_args()
    stale = []
    for kit, spec in KITS.items():
        target = ROOT / 'antigravity/plugins' / kit / 'rules/AGENTS.md'
        content = render(kit, spec)
        size = len(content.encode())
        if size > LIMIT:
            print(f'::error::{target.relative_to(ROOT)} is {size} bytes, over the {LIMIT} byte rule limit')
            return 1
        if args.check:
            if not target.exists() or target.read_text() != content:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            print(f'wrote {target.relative_to(ROOT)} ({size} bytes)')
    if stale:
        for path in stale:
            print(f'::error::{path} is stale, run python3 antigravity/scripts/sync_rules.py')
        return 1
    if args.check:
        print('sync_rules: generated rules are current')
    return 0


if __name__ == '__main__':
    sys.exit(main())
